import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { Alert, Box, Button, Chip, Divider, FormControl, Grid, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { AddRounded, DownloadRounded, ReceiptLongRounded, RefreshRounded, PaymentsRounded } from '@mui/icons-material';
import { useSelector } from 'react-redux';
import { KpiCard, PremiumCard, SectionHeader } from '../../../components/PremiumShell';

const API = process.env.REACT_APP_API_URL || 'http://localhost:5000';
const currency = n => `₹${Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateText = d => d ? new Date(d).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }) : '—';

export default function FeeManagement() {
  const { currentUser } = useSelector(s => s.user);
  const { studentsList = [] } = useSelector(s => s.student);
  const adminID = currentUser?._id;
  const [invoices, setInvoices] = useState([]), [report, setReport] = useState(null), [payments, setPayments] = useState([]);
  const [selectedStudent, setSelectedStudent] = useState(''), [status, setStatus] = useState('All'), [academicYear, setAcademicYear] = useState('2026-27');
  const [loading, setLoading] = useState(false), [message, setMessage] = useState(''), [tab, setTab] = useState('invoices');
  const [invoiceForm, setInvoiceForm] = useState({ studentId:'', term:'Tuition Fee', item:'Tuition Fee', amount:'', discount:'0', tax:'0', dueDate:'', notes:'' });
  const [paymentForm, setPaymentForm] = useState({ invoiceId:'', amount:'', method:'UPI', transactionId:'', remarks:'' });

  const load = async () => {
    if (!adminID) return; setLoading(true); setMessage('');
    try { const [i,p,r] = await Promise.all([
      axios.get(`${API}/Fees/Invoices/${adminID}`, {params:{status,academicYear}}), axios.get(`${API}/Fees/Payments/${adminID}`), axios.get(`${API}/Fees/Report/${adminID}`, {params:{academicYear}})
    ]); setInvoices(i.data); setPayments(p.data); setReport(r.data); }
    catch(e){ setMessage(e.response?.data?.message || 'Unable to load fee data. Check the backend connection.'); }
    finally { setLoading(false); }
  };
  useEffect(()=>{load()},[adminID,status,academicYear]);
  const visibleInvoices = useMemo(()=>selectedStudent?invoices.filter(i=>i.student?._id===selectedStudent):invoices,[invoices,selectedStudent]);

  const createInvoice = async e => { e.preventDefault(); setMessage(''); try {
    await axios.post(`${API}/Fees/InvoiceCreate`, {adminID,studentId:invoiceForm.studentId,academicYear,term:invoiceForm.term,dueDate:invoiceForm.dueDate,discount:Number(invoiceForm.discount||0),tax:Number(invoiceForm.tax||0),notes:invoiceForm.notes,lineItems:[{title:invoiceForm.item,amount:Number(invoiceForm.amount||0)}]});
    setInvoiceForm({studentId:'',term:'Tuition Fee',item:'Tuition Fee',amount:'',discount:'0',tax:'0',dueDate:'',notes:''}); setMessage('Invoice created successfully.'); await load();
  } catch(e){setMessage(e.response?.data?.message||'Could not create invoice.');} };

  const printReceipt = payment => { const student=payment.student||{}, invoice=payment.invoice||{}; const w=window.open('','_blank','width=760,height=850'); if(!w)return;
    w.document.write(`<html><head><title>${payment.receiptNumber}</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#172033}h1{margin-bottom:4px}.muted{color:#667085}.row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #eee}.total{font-size:24px;font-weight:700;margin-top:24px}</style></head><body><h1>EduFlow School</h1><div class="muted">Official Fee Payment Receipt</div><hr/><div class="row"><b>Receipt</b><span>${payment.receiptNumber}</span></div><div class="row"><b>Invoice</b><span>${invoice.invoiceNumber||'—'}</span></div><div class="row"><b>Student</b><span>${student.name||'—'} ${student.rollNum?`(Roll ${student.rollNum})`:''}</span></div><div class="row"><b>Payment date</b><span>${dateText(payment.paidAt)}</span></div><div class="row"><b>Method</b><span>${payment.method}</span></div><div class="row"><b>Transaction ID</b><span>${payment.transactionId||'—'}</span></div><div class="total">Amount received: ${currency(payment.amount)}</div><p class="muted">System-generated receipt.</p><script>window.onload=()=>window.print()</script></body></html>`); w.document.close(); };
  const recordPayment = async e => { e.preventDefault(); setMessage(''); try { const {data}=await axios.post(`${API}/Fees/PaymentCreate`,{...paymentForm,adminID,amount:Number(paymentForm.amount)}); setMessage(`Payment recorded. Receipt ${data.receiptNumber}`); setPaymentForm({invoiceId:'',amount:'',method:'UPI',transactionId:'',remarks:''}); await load(); printReceipt(data); } catch(e){setMessage(e.response?.data?.message||'Could not record payment.');} };
  const exportCsv = () => { const rows=[['Invoice','Student','Academic Year','Term','Total','Paid','Balance','Status','Due Date'],...invoices.map(i=>[i.invoiceNumber,i.student?.name||'',i.academicYear,i.term,i.totalAmount,i.paidAmount,i.balance,i.status,dateText(i.dueDate)])]; const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`fee-report-${academicYear}.csv`; a.click(); URL.revokeObjectURL(a.href); };

  return <Box>
    {message && <Alert sx={{mb:2}} severity={message.includes('successfully')||message.includes('recorded')?'success':'info'} onClose={()=>setMessage('')}>{message}</Alert>}
    <Grid container spacing={2} sx={{mb:2}}>
      <Grid item xs={12} sm={6} md={3}><KpiCard icon={ReceiptLongRounded} label="Invoices" value={report?.invoiceCount??'—'} helper="Issued in selected year" tone="blue"/></Grid>
      <Grid item xs={12} sm={6} md={3}><KpiCard icon={PaymentsRounded} label="Collected" value={currency(report?.collected)} helper={`${report?.collectionRate??0}% collection rate`} tone="green"/></Grid>
      <Grid item xs={12} sm={6} md={3}><KpiCard icon={ReceiptLongRounded} label="Outstanding" value={currency(report?.outstanding)} helper="Pending balance" tone="orange"/></Grid>
      <Grid item xs={12} sm={6} md={3}><KpiCard icon={PaymentsRounded} label="Overdue" value={currency(report?.overdue)} helper="Past due balance" tone="violet"/></Grid>
    </Grid>
    <PremiumCard>
      <SectionHeader eyebrow="Finance workspace" title="Fees & invoices" action={<Stack direction="row" spacing={1}><Button startIcon={<RefreshRounded/>} onClick={load} disabled={loading}>Refresh</Button><Button startIcon={<DownloadRounded/>} variant="outlined" onClick={exportCsv}>Export CSV</Button></Stack>}/>
      <Stack direction={{xs:'column',md:'row'}} spacing={2} sx={{mb:2}}>
        <FormControl size="small" sx={{minWidth:180}}><InputLabel>Academic year</InputLabel><Select value={academicYear} label="Academic year" onChange={e=>setAcademicYear(e.target.value)}><MenuItem value="2025-26">2025-26</MenuItem><MenuItem value="2026-27">2026-27</MenuItem><MenuItem value="2027-28">2027-28</MenuItem></Select></FormControl>
        <FormControl size="small" sx={{minWidth:180}}><InputLabel>Status</InputLabel><Select value={status} label="Status" onChange={e=>setStatus(e.target.value)}>{['All','Pending','Partially Paid','Paid','Overdue'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl>
        <FormControl size="small" sx={{minWidth:220}}><InputLabel>Student</InputLabel><Select value={selectedStudent} label="Student" onChange={e=>setSelectedStudent(e.target.value)}><MenuItem value="">All students</MenuItem>{studentsList.map(s=><MenuItem key={s._id} value={s._id}>{s.name} · {s.rollNum}</MenuItem>)}</Select></FormControl>
      </Stack>
      <Stack direction="row" spacing={1} sx={{mb:2}}>{[['invoices','Invoices'],['payment','Collect payment'],['reports','Reports']].map(([v,l])=><Button key={v} variant={tab===v?'contained':'text'} onClick={()=>setTab(v)}>{l}</Button>)}</Stack><Divider sx={{mb:2}}/>
      {tab==='invoices' && <Box sx={{overflowX:'auto'}}><Table size="small"><TableHead><TableRow>{['Invoice','Student','Term','Total','Paid','Balance','Due','Status'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{visibleInvoices.map(i=><TableRow key={i._id} hover><TableCell><b>{i.invoiceNumber}</b></TableCell><TableCell>{i.student?.name||'—'}<br/><small>{i.student?.rollNum?`Roll ${i.student.rollNum}`:''}</small></TableCell><TableCell>{i.term}</TableCell><TableCell>{currency(i.totalAmount)}</TableCell><TableCell>{currency(i.paidAmount)}</TableCell><TableCell><b>{currency(i.balance)}</b></TableCell><TableCell>{dateText(i.dueDate)}</TableCell><TableCell><Chip size="small" label={i.status} color={i.status==='Paid'?'success':i.status==='Overdue'?'error':i.status==='Partially Paid'?'warning':'default'}/></TableCell></TableRow>)}{!visibleInvoices.length&&<TableRow><TableCell colSpan={8}><Typography sx={{p:3,textAlign:'center'}} color="text.secondary">No invoices found.</Typography></TableCell></TableRow>}</TableBody></Table></Box>}
      {tab==='payment' && <Grid container spacing={3}><Grid item xs={12} md={6}><Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6" sx={{mb:2}}>Record payment</Typography><Box component="form" onSubmit={recordPayment}><Stack spacing={2}><FormControl fullWidth required><InputLabel>Invoice</InputLabel><Select value={paymentForm.invoiceId} label="Invoice" onChange={e=>{const id=e.target.value,inv=invoices.find(x=>x._id===id);setPaymentForm(f=>({...f,invoiceId:id,amount:inv?.balance||''}))}}>{invoices.filter(i=>i.balance>0).map(i=><MenuItem key={i._id} value={i._id}>{i.invoiceNumber} · {i.student?.name} · {currency(i.balance)} due</MenuItem>)}</Select></FormControl><TextField label="Amount" type="number" inputProps={{min:0,step:'0.01'}} value={paymentForm.amount} onChange={e=>setPaymentForm(f=>({...f,amount:e.target.value}))} required/><FormControl fullWidth><InputLabel>Method</InputLabel><Select value={paymentForm.method} label="Method" onChange={e=>setPaymentForm(f=>({...f,method:e.target.value}))}>{['Cash','UPI','Card','Bank Transfer','Cheque','Other'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><TextField label="Transaction / reference ID" value={paymentForm.transactionId} onChange={e=>setPaymentForm(f=>({...f,transactionId:e.target.value}))}/><TextField label="Remarks" multiline minRows={2} value={paymentForm.remarks} onChange={e=>setPaymentForm(f=>({...f,remarks:e.target.value}))}/><Button type="submit" variant="contained" startIcon={<PaymentsRounded/>}>Record payment & print receipt</Button></Stack></Box></Paper></Grid><Grid item xs={12} md={6}><Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6" sx={{mb:2}}>Recent payments</Typography><Stack spacing={1.5}>{payments.slice(0,8).map(p=><Box key={p._id} sx={{p:1.5,border:'1px solid',borderColor:'divider',borderRadius:2,cursor:'pointer'}} onClick={()=>printReceipt(p)}><Stack direction="row" justifyContent="space-between"><b>{p.receiptNumber}</b><strong>{currency(p.amount)}</strong></Stack><Typography variant="body2">{p.student?.name} · {p.method}</Typography><Typography variant="caption" color="text.secondary">{dateText(p.paidAt)} · Click to print receipt</Typography></Box>)}</Stack></Paper></Grid></Grid>}
      {tab==='reports' && <Grid container spacing={2}><Grid item xs={12} md={7}><Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6">Collection summary</Typography><Stack spacing={2} sx={{mt:2}}>{[['Total invoiced',report?.invoiced],['Collected',report?.collected],['Outstanding',report?.outstanding],['Overdue',report?.overdue]].map(([l,v])=><Stack direction="row" justifyContent="space-between" key={l}><Typography>{l}</Typography><Typography fontWeight={700}>{currency(v)}</Typography></Stack>)}</Stack></Paper></Grid><Grid item xs={12} md={5}><Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6">Payment methods</Typography><Stack spacing={1.5} sx={{mt:2}}>{Object.entries(report?.byMethod||{}).map(([method,value])=><Stack direction="row" justifyContent="space-between" key={method}><Typography>{method}</Typography><Typography fontWeight={700}>{currency(value)}</Typography></Stack>)}</Stack></Paper></Grid></Grid>}
    </PremiumCard>
    <PremiumCard sx={{mt:2}}><SectionHeader eyebrow="Create" title="Issue a new fee invoice" action={<AddRounded className="muted-icon"/>}/><Box component="form" onSubmit={createInvoice}><Grid container spacing={2}><Grid item xs={12} md={4}><FormControl fullWidth required><InputLabel>Student</InputLabel><Select value={invoiceForm.studentId} label="Student" onChange={e=>setInvoiceForm(f=>({...f,studentId:e.target.value}))}>{studentsList.map(s=><MenuItem key={s._id} value={s._id}>{s.name} · {s.rollNum}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={4}><TextField fullWidth label="Fee item" value={invoiceForm.item} onChange={e=>setInvoiceForm(f=>({...f,item:e.target.value}))} required/></Grid><Grid item xs={12} md={4}><TextField fullWidth label="Amount" type="number" value={invoiceForm.amount} onChange={e=>setInvoiceForm(f=>({...f,amount:e.target.value}))} required/></Grid><Grid item xs={12} md={3}><TextField fullWidth label="Term" value={invoiceForm.term} onChange={e=>setInvoiceForm(f=>({...f,term:e.target.value}))}/></Grid><Grid item xs={12} md={3}><TextField fullWidth label="Discount" type="number" value={invoiceForm.discount} onChange={e=>setInvoiceForm(f=>({...f,discount:e.target.value}))}/></Grid><Grid item xs={12} md={3}><TextField fullWidth label="Tax" type="number" value={invoiceForm.tax} onChange={e=>setInvoiceForm(f=>({...f,tax:e.target.value}))}/></Grid><Grid item xs={12} md={3}><TextField fullWidth label="Due date" type="date" InputLabelProps={{shrink:true}} value={invoiceForm.dueDate} onChange={e=>setInvoiceForm(f=>({...f,dueDate:e.target.value}))} required/></Grid><Grid item xs={12}><TextField fullWidth label="Notes" value={invoiceForm.notes} onChange={e=>setInvoiceForm(f=>({...f,notes:e.target.value}))}/></Grid><Grid item xs={12}><Button type="submit" variant="contained" startIcon={<AddRounded/>}>Create invoice</Button></Grid></Grid></Box></PremiumCard>
  </Box>;
}
