import React from "react";
import { Link } from "react-router-dom";
import { Box, Button, Chip, Typography } from "@mui/material";
import { ArrowForwardRounded, CheckCircleRounded, DashboardRounded, GroupsRounded, InsightsRounded, SecurityRounded } from "@mui/icons-material";
import { PremiumCard } from "../components/PremiumShell";

const Homepage=()=>(
 <Box className="landing">
    <Box className="landing-nav"><Box className="brand"><Box className="brand-mark"><DashboardRounded/></Box><Box><Typography className="brand-name">School<span>Nex</span></Typography><Typography className="brand-sub">School OS</Typography></Box></Box><Box className="landing-links"><a href="#features">Features</a><a href="#roles">For schools</a><a href="#security">Secure by design</a><Link to="/choose"><Button variant="contained" endIcon={<ArrowForwardRounded/>}>Sign in</Button></Link></Box></Box>
    <Box className="landing-hero"><Box className="landing-copy"><Chip label="Modern school management platform" className="hero-chip"/><Typography className="landing-title">Run your school with <span>clarity.</span></Typography><Typography className="landing-subtitle">A premium workspace for administrators, teachers and students—built around the workflows your campus already uses.</Typography><Box className="landing-actions"><Link to="/choose"><Button variant="contained" size="large" endIcon={<ArrowForwardRounded/>}>Open dashboard</Button></Link><Link to="/chooseasguest"><Button variant="outlined" size="large">Explore as guest</Button></Link></Box><Box className="proof-row"><span><CheckCircleRounded/> Attendance</span><span><CheckCircleRounded/> Academics</span><span><CheckCircleRounded/> Communication</span></Box></Box>
    <PremiumCard className="hero-preview"><Box className="preview-top"><span className="preview-dot"></span><span className="preview-dot"></span><span className="preview-dot"></span><small>SchoolNex • Admin</small></Box><Box className="preview-content"><Typography className="eyebrow">Campus overview</Typography><Typography className="preview-title">Good morning, Admin 👋</Typography><Box className="preview-kpis"><div><small>Students</small><b>1,284</b><em>+8.2%</em></div><div><small>Teachers</small><b>86</b><em>+3.1%</em></div><div><small>Attendance</small><b>92%</b><em>Healthy</em></div></Box><Box className="fake-chart"><span style={{height:"42%"}}></span><span style={{height:"61%"}}></span><span style={{height:"50%"}}></span><span style={{height:"76%"}}></span><span style={{height:"68%"}}></span><span style={{height:"91%"}}></span><span style={{height:"83%"}}></span></Box></Box></PremiumCard></Box>
  <Box id="features" className="landing-features"><Typography className="eyebrow">Everything connected</Typography><Typography className="feature-title">The essentials, without the clutter.</Typography><Box className="feature-grid"><Feature icon={GroupsRounded} title="People & roles" text="Students, teachers, classes and profiles in one consistent system."/><Feature icon={InsightsRounded} title="Performance" text="Attendance, marks and academic progress surfaced as actionable insights."/><Feature icon={SecurityRounded} title="Controlled access" text="Role-based workspaces keep every user focused on what they need." /></Box></Box>
  <Box id="roles" className="landing-bottom"><Typography>Ready to modernize your campus?</Typography><Link to="/choose"><Button variant="contained" endIcon={<ArrowForwardRounded/>}>Choose your workspace</Button></Link></Box>
 </Box>
);
const Feature=({icon:Icon,title,text})=><Box className="feature"><Box className="feature-icon"><Icon/></Box><Typography>{title}</Typography><small>{text}</small></Box>;
export default Homepage;
